### PR TITLE
tags support

### LINKED ISSUE #82: CLI tags support
## Problem

We're adding support for tags in titan-server, we need to add that to the CLI.

## Solution

Implement CLI methods to manage tags:

- log filter by tag
- push/pull metadata only
- tag existing commit
- delete existing tag

### LINKED ISSUE #87: push/pull doesn't report all information
## Expected Behavior

```
$ titan push postgres
Pushing 4d8924cf9905462e9e02fd97b8ab4d15 to 'origin'
push operations are not supported for s3web provider
Push failed
```

## Actual Behavior

```
$ titan push postgres
PUSH 4d8924cf9905462e9e02fd97b8ab4d15 to origin RUNNING
Pushing 4d8924cf9905462e9e02fd97b8ab4d15 to 'origin'
PUSH 4d8924cf9905462e9e02fd97b8ab4d15 to origin FAILED
```

The issue is that we're keying off the operation state, not the last progress entry. So we get the initial status, check the operation, see it's failed, and break. But there are more progress entries to be consumed.

## Steps to Reproduce the Problem

Try to push to an s3web origin

## Version

0.3.4

### LINKED ISSUE #88: Ctrl-C during push/pull should abort the operation
## Expected Behavior

When I interrupt a push/pull, it should abort the operation running on the server.

## Actual Behavior

The CLI command exits, but the operation remains running.

## Steps to Reproduce the Problem

Type Ctrl-C during a long-running push or pull.

## Version

0.3.4

### PR DESCRIPTION
**Pull request by eschrock**
## Issues Addressed

Fixes #82 
Fixes #87 
Fixes #88 

## Proposed Changes

This strings together all the changes to support tags. Other things fixed along the way include cleaning up the progress reporting (just enough while we wait to do a more complete refactor), and augmenting the "checkout" command to default to latest (matching) commit if none is specified.

I also went ahead and added the source commit to the metadata and repo status, since I bumped the titan-server version to 0.5.1.

## Testing

Lots of manual testing.

### CODE REVIEW

File: src/main/kotlin/io/titandata/titan/Cli.kt [hunk 1]
```diff
@@ -32,7 +34,19 @@ object Cli {
...
+            val logging = HttpLoggingInterceptor()
+            if (titanDebug.equals("trace", true)) {
+                logging.level = HttpLoggingInterceptor.Level.BODY
+            } else {
+                logging.level = HttpLoggingInterceptor.Level.BASIC
+            }
+            ApiClient.builder.addInterceptor(logging)
+        }
+
         BasicConfigurator.configure();
```
Comment (mcred) [inline src/main/kotlin/io/titandata/titan/Cli.kt]: We're kind of stacking logging here. What do you think about using slf4j since it's already required by the AWS SDK?

File: src/main/kotlin/io/titandata/titan/providers/local/Checkout.kt [hunk 2]
```diff
@@ -5,21 +5,44 @@
...
 
 class Checkout (
         private val commandExecutor: CommandExecutor = CommandExecutor(),
         private val docker: Docker = Docker(commandExecutor),
-        private val commitsApi: CommitsApi = CommitsApi()
+        private val commitsApi: CommitsApi = CommitsApi(),
+        private val repositoriesApi: RepositoriesApi = RepositoriesApi()
 ) {
-    fun checkout(container: String, guid: String) {
+    fun checkout(container: String, commit: String?, tags: List<String>) {
```
Comment (mcred) [inline src/main/kotlin/io/titandata/titan/providers/local/Checkout.kt]: Commit is an object in the client SDK, this is why I used guid: String instead of commit: String. We want a GUID string here, not a commit.

File: src/main/kotlin/io/titandata/titan/providers/local/Checkout.kt [hunk 3]
```diff
@@ -5,21 +5,44 @@
...
+        var sourceCommit = if (commit == null) {
```
Comment (mcred) [inline src/main/kotlin/io/titandata/titan/providers/local/Checkout.kt]: is sourceCommit ever altered? it looks immutable with the if statements. Should it be `val sourceCommit`?

File: src/main/kotlin/io/titandata/titan/providers/local/Commit.kt [hunk 4]
```diff
@@ -16,18 +16,34 @@ class Commit (
...
     private val uuid: String = UUID.randomUUID().toString().replace("-","")
 ) {
-    fun commit(container: String, message: String) {
+    fun commit(container: String, message: String, tags: List<String>) {
         val repoMetadata = repositoriesApi.getRepository(container).properties
-        val metadata = mapOf(
+        val repoStatus = repositoriesApi.getRepositoryStatus(container)
+        val sourceCommit = repoStatus.sourceCommit
+        val tagMetadata = mutableMapOf<String, String>()
+        for (t in tags) {
```
Comment (mcred) [inline src/main/kotlin/io/titandata/titan/providers/local/Commit.kt]: I prefer `for (tag in tags)`. I'm not a fan of single char variable names for the most part. The only exception is `i` for `i--` and `i++`.

File: src/main/kotlin/io/titandata/titan/providers/local/Delete.kt [hunk 5]
```diff
@@ -13,4 +13,26 @@ class Delete (
...
         println("$commit deleted")
     }
+
+    fun deleteTags(repository: String, commit: String, tags: List<String>) {
+        val commit = commitsApi.getCommit(repository, commit)
+        val commitTags = (commit.properties.get("tags") as Map<String, String>).toMutableMap()
+
+        for (t in tags) {
+            if (t.contains("=")) {
+                val key = t.substringBefore("=")
```
Comment (mcred) [inline src/main/kotlin/io/titandata/titan/providers/local/Delete.kt]: Is there any validation for a string that contains more than 1 = ?

File: src/main/kotlin/io/titandata/titan/providers/local/Migrate.kt [hunk 6]
```diff
@@ -101,7 +101,7 @@ class Migrate (
         val updateRepo = Repository(name, metadata)
         repositoriesApi.updateRepository(name, updateRepo)
         docker.run(image, "", arguments)
-        commit(name, "Initial Migration")
+        commit(name, "Initial Migration", listOf())
```
Comment (mcred) [inline src/main/kotlin/io/titandata/titan/providers/local/Migrate.kt]: ` emptyList<String>()` is probably better than `listOf()` because it declares the type and that it's empty.

File: src/main/kotlin/io/titandata/titan/providers/local/RemoteLog.kt [hunk 7]
```diff
@@ -59,6 +60,22 @@ class RemoteLog (
                         println("Email: ${commit.properties["email"]}")
                     }
                     println("Date:   ${commit.properties["timestamp"]}")
+                    if (commit.properties.containsKey("tags")) {
+                        @Suppress("UNCHECKED_CAST")
```
Comment (mcred) [inline src/main/kotlin/io/titandata/titan/providers/local/RemoteLog.kt]: Why do you use the `@Suppress` here but not in local/Log.kt?

File: src/main/kotlin/io/titandata/titan/providers/local/Tag.kt [hunk 8]
```diff
@@ -0,0 +1,35 @@
...
+ */
+
+package io.titandata.titan.providers.local
+
+import io.titandata.client.apis.CommitsApi
+
+class Tag (
+    private val commitsApi: CommitsApi = CommitsApi()
+) {
+    fun tagCommit(repository: String, commit: String, tags: List<String>) {
```
Comment (mcred) [inline src/main/kotlin/io/titandata/titan/providers/local/Tag.kt]: Can we consistently use `guid: String` instead of `commit`?

File: src/main/kotlin/io/titandata/titan/Cli.kt (hunk 1 above)
Comment (eschrock) [reply src/main/kotlin/io/titandata/titan/Cli.kt]: OKHttp does use slf4j. This is just how you add the interceptor to enable it.

File: src/main/kotlin/io/titandata/titan/providers/local/Delete.kt (hunk 5 above)
Comment (eschrock) [reply src/main/kotlin/io/titandata/titan/providers/local/Delete.kt]: No, because that's totally legal. You can definitely do "foo=bar=baz". That will equate to ("foo", "bar=baz"). Weird, but that's why I use subStringBefore and not substringBeforeLast.

File: src/main/kotlin/io/titandata/titan/providers/local/Tag.kt (hunk 8 above)
Comment (eschrock) [reply src/main/kotlin/io/titandata/titan/providers/local/Tag.kt]: I guess I'm confused. Looking at Provider.kt, there are a half dozen commands that take a commit ID. They are all called "commit". The only exception is checkout(). I'm happy to leave that one as-is, but I see no reason why tag should be different than delete/push/pull/etc. They all take commit IDs and the parameter is named "commit" (along with the CLI option is "-c" for commit).

File: src/main/kotlin/io/titandata/titan/providers/local/RemoteLog.kt (hunk 7 above)
Comment (eschrock) [reply src/main/kotlin/io/titandata/titan/providers/local/RemoteLog.kt]: Just because I noticed the warning (we don't have warnings as errors turned on to keep these from creeping in). The other one got lost in the list of existing ones, will address there as well.

File: src/main/kotlin/io/titandata/titan/providers/local/Tag.kt (hunk 8 above)
Comment (mcred) [reply src/main/kotlin/io/titandata/titan/providers/local/Tag.kt]: You're right. I forgot we're in the provider scope here. It should be commit.

Comment (mcred) [reply src/main/kotlin/io/titandata/titan/providers/local/Tag.kt]: For the CLI and the end user, it should definitely be commit. I prefer GUID in the provider side, I know I ran into confusion once and switched to GUID. I guess I didn't go back and refactor all the other instances of commit: String to guid: String in the providers. Small nit here.

Comment (eschrock) [reply src/main/kotlin/io/titandata/titan/providers/local/Tag.kt]: OK I'll leave it for now since it matches the others. I've gotten enough scope creep at this point, can come and refactor the others once we have end2end tests and can be a bit more confident making changes.
